// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CCard: typeof import('./src/components/CCard.vue')['default']
    CTextarea: typeof import('./src/components/CTextarea.vue')['default']
    CypherLogo: typeof import('./src/components/images/CypherLogo.vue')['default']
  }
}

export { }
