// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    PageTitle: typeof import('./src/components/PageTitle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserInfo: typeof import('./src/components/UserInfo.vue')['default']
    VButton: typeof import('./src/components/VButton.vue')['default']
  }
}
